import React, {Fragment} from 'react'

export const About = () => (
    <Fragment>
        
        <h1>About</h1>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id ad voluptatum accusantium quibusdam suscipit aspernatur facilis dolor molestias libero rem a fugit tempore magnam placeat, cum nulla illo quia recusandae? Iusto dignissimos corrupti, blanditiis labore nostrum nihil necessitatibus sint? Cum, vel et debitis praesentium distinctio esse placeat laboriosam obcaecati eaque deserunt, iste hic ratione quis voluptatum quo magnam, veritatis tenetur sint molestias voluptatibus! Ex atque accusamus, nemo porro, ratione quos corrupti vel qui eligendi est nobis? Porro rerum minima pariatur magnam amet quo possimus itaque ex ad, earum perferendis quia tenetur! Eius modi eum dolor sunt! Animi, doloribus molestiae odit saepe atque explicabo minus pariatur voluptate unde dolorem dolores quam. Eveniet distinctio, nihil nam eum aut magni laboriosam iste deserunt ea omnis rerum perferendis aspernatur id. Quisquam ratione quod nisi deserunt nesciunt molestias eaque, sed placeat nam expedita officiis quaerat earum in perspiciatis temporibus culpa ab aperiam. Incidunt ex nobis ea? Placeat mollitia aut numquam architecto nobis voluptates dolores dignissimos distinctio sequi, perspiciatis veritatis reprehenderit enim, iste perferendis a doloremque molestiae ipsa ullam quidem provident ipsum. Quos inventore qui odio placeat, molestiae repellat autem perspiciatis delectus ipsa nam quibusdam asperiores, unde vel hic porro consectetur praesentium voluptatibus temporibus quam eligendi? Voluptates deserunt quo totam repudiandae et saepe nobis ipsa voluptatum ea fuga quam esse repellat, sit quibusdam repellendus. Ab rerum, excepturi id reprehenderit ipsum cupiditate quasi nihil aspernatur incidunt. Dolores voluptatibus cumque eos. Totam libero soluta eaque, non, quibusdam corporis ducimus dolore asperiores quas expedita aspernatur culpa doloremque ea reiciendis inventore repudiandae quaerat, corrupti ullam dolor ut! Eveniet dolore impedit accusamus, dolorem quis adipisci facilis. Vitae harum quidem cupiditate debitis incidunt, fuga quos voluptate nam dolorem obcaecati pariatur cum blanditiis qui officiis, porro sapiente enim voluptatum. Quae suscipit dolorum vel! Dolorem quasi quam minima dolores qui harum amet officiis expedita!</p>

        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, impedit voluptatibus explicabo natus unde blanditiis iusto aliquam porro consectetur laborum debitis quaerat saepe nostrum ab quod! Libero, mollitia nostrum. Vel dolor eligendi voluptas accusantium corrupti vero, molestiae consectetur amet ipsam ex et repellendus aspernatur quaerat, commodi, excepturi numquam eveniet! Magni quae fuga obcaecati, fugiat earum omnis culpa beatae dolore laudantium animi doloremque voluptatum iste mollitia aliquid, molestiae vero dicta accusantium itaque placeat, ratione incidunt quibusdam natus. Neque molestiae quae eius dolorum quam est ipsa iure, ut quibusdam sapiente temporibus et sequi asperiores maiores labore voluptatum eligendi obcaecati exercitationem, aperiam cum!</p>
    </Fragment>
)